
import { Hero, HeroRole, AttackType } from './types';

export const HEROES: Hero[] = [
  // Captains
  { id: 'adagio', name: 'Adagio', cnName: '天使', role: HeroRole.CAPTAIN, attackType: AttackType.RANGED, imageIndex: 1 },
  { id: 'ardan', name: 'Ardan', cnName: '二蛋', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 4 },
  { id: 'catherine', name: 'Catherine', cnName: '凯瑟琳', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 8 },
  { id: 'churnwalker', name: 'Churnwalker', cnName: '沃克尔', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 10 },
  { id: 'flicker', name: 'Flicker', cnName: '弗利克', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 11 },
  { id: 'fortress', name: 'Fortress', cnName: '魔狼', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 12 },
  { id: 'grace', name: 'Grace', cnName: '格蕾丝', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 14 },
  { id: 'lance', name: 'Lance', cnName: '兰斯', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 26 },
  { id: 'lorelai', name: 'Lorelai', cnName: '蛇女', role: HeroRole.CAPTAIN, attackType: AttackType.RANGED, imageIndex: 28 },
  { id: 'lyra', name: 'Lyra', cnName: '莱拉', role: HeroRole.CAPTAIN, attackType: AttackType.RANGED, imageIndex: 29 },
  { id: 'phinn', name: 'Phinn', cnName: '鱼人', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 35 },
  { id: 'viola', name: 'Viola', cnName: '维奥拉', role: HeroRole.CAPTAIN, attackType: AttackType.RANGED, imageIndex: 48 },
  { id: 'yates', name: 'Yates', cnName: '耶茨', role: HeroRole.CAPTAIN, attackType: AttackType.MELEE, imageIndex: 51 },

  // Jungle
  { id: 'alpha', name: 'Alpha', cnName: '阿尔法', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 2 },
  { id: 'anka', name: 'Anka', cnName: '安卡', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 3 },
  { id: 'baptiste', name: 'Baptiste', cnName: '巴蒂斯特', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 5 },
  { id: 'glaive', name: 'Glaive', cnName: '豹子', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 13 },
  { id: 'grumpjaw', name: 'Grumpjaw', cnName: '大嘴', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 15 },
  { id: 'inara', name: 'Inara', cnName: '伊娜', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 18 },
  { id: 'joule', name: 'Joule', cnName: '朱尔', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 20 },
  { id: 'koshka', name: 'Koshka', cnName: '柯思卡', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 24 },
  { id: 'krul', name: 'Krul', cnName: '鬼剑', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 25 },
  { id: 'ozo', name: 'Ozo', cnName: '猴子', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 33 },
  { id: 'petal', name: 'Petal', cnName: '花花', role: HeroRole.JUNGLE, attackType: AttackType.RANGED, imageIndex: 34 },
  { id: 'reim', name: 'Reim', cnName: '冰法', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 36 },
  { id: 'reza', name: 'Reza', cnName: '火法', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 37 },
  { id: 'rona', name: 'Rona', cnName: '罗娜', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 39 },
  { id: 'shin', name: 'Shin', cnName: '哪吒', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 99 },
  { id: 'taka', name: 'Taka', cnName: '塔卡', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 45 },
  { id: 'tony', name: 'Tony', cnName: '托尼', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 46 },
  { id: 'ylva', name: 'Ylva', cnName: '伊娃', role: HeroRole.JUNGLE, attackType: AttackType.MELEE, imageIndex: 52 },

  // Carry
  { id: 'amael', name: 'Amael', cnName: '牛头', role: HeroRole.CARRY, attackType: AttackType.MELEE, imageIndex: 100 },
  { id: 'baron', name: 'Baron', cnName: '巴隆', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 6 },
  { id: 'blackfeather', name: 'Blackfeather', cnName: '黑羽', role: HeroRole.CARRY, attackType: AttackType.MELEE, imageIndex: 7 },
  { id: 'caine', name: 'Caine', cnName: '凯恩', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 102 },
  { id: 'celeste', name: 'Celeste', cnName: '星乐斯', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 9 },
  { id: 'gwen', name: 'Gwen', cnName: '格温', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 16 },
  { id: 'idris', name: 'Idris', cnName: '伊德瑞', role: HeroRole.CARRY, attackType: AttackType.MELEE, imageIndex: 17 },
  { id: 'ishtar', name: 'Ishtar', cnName: '伊斯塔', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 19 },
  { id: 'karas', name: 'Karas', cnName: '鸦', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 103 },
  { id: 'kensei', name: 'Kensei', cnName: '剑圣', role: HeroRole.CARRY, attackType: AttackType.MELEE, imageIndex: 21 },
  { id: 'kestrel', name: 'Kestrel', cnName: '凯思卓', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 22 },
  { id: 'kinetic', name: 'Kinetic', cnName: '基尼', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 23 },
  { id: 'leo', name: 'Leo', cnName: '里昂', role: HeroRole.CARRY, attackType: AttackType.MELEE, imageIndex: 27 },
  { id: 'magnus', name: 'Magnus', cnName: '马格纳斯', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 30 },
  { id: 'malene', name: 'Malene', cnName: '小公主', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 31 },
  { id: 'miho', name: 'Miho', cnName: '美惠', role: HeroRole.CARRY, attackType: AttackType.MELEE, imageIndex: 32 },
  { id: 'ringo', name: 'Ringo', cnName: '林戈', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 38 },
  { id: 'samuel', name: 'Samuel', cnName: '萨缪尔', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 40 },
  { id: 'sanfeng', name: 'San Feng', cnName: '三丰', role: HeroRole.CARRY, attackType: AttackType.MELEE, imageIndex: 101 },
  { id: 'saw', name: 'SAW', cnName: '索尔', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 41 },
  { id: 'silvernail', name: 'Silvernail', cnName: '银钉', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 42 },
  { id: 'skaarf', name: 'Skaarf', cnName: '火龙', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 43 },
  { id: 'skye', name: 'Skye', cnName: '斯凯依', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 44 },
  { id: 'varya', name: 'Varya', cnName: '瓦尼亚', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 47 },
  { id: 'vox', name: 'Vox', cnName: '沃克斯', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 49 },
  { id: 'warhawk', name: 'Warhawk', cnName: '尼尔', role: HeroRole.CARRY, attackType: AttackType.RANGED, imageIndex: 50 },
];
